Attempt to fix test_common_controls.TreeViewAdditionalTestCases.test_expand_collapse_buttons
Probable cause: a single click and a half of double click are perceived
as a whole double click (default DoubleClickSpeed value is 500 ms)

Traceback:
  File "C:\projects\pywinauto\pywinauto\unittests\test_common_controls.py", line 767, in test_expand_collapse_buttons
    self.assertEqual(birds.is_expanded(), True)
AssertionError: False != True